name: ai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - python-dotenv
  - requests
  - pytorch
  - jupyterlab
  - ipykernel
  - pip:
    - transformers
    - openai
    - anthropic
    - ollama